In [3]:
import pandas as pd
import numpy as np 

In [4]:
#give column names to dataset 

In [5]:


file_path = "ecoli.data"
column_names = ["Sequence Name", "mcg", "gvh", "lip", "chg", "aac", "alm1", "alm2", "class"]

In [6]:
#read the data and assign the column name the dataset

In [7]:

readFile = pd.read_csv(file_path, sep='\\s+', names=column_names)
#print the  top 5 element  
print(readFile)


    Sequence Name   mcg   gvh   lip  chg   aac  alm1  alm2 class
0       AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35    cp
1      ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44    cp
2      ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46    cp
3      ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36    cp
4       ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35    cp
..            ...   ...   ...   ...  ...   ...   ...   ...   ...
331    TREA_ECOLI  0.74  0.56  0.48  0.5  0.47  0.68  0.30    pp
332    UGPB_ECOLI  0.71  0.57  0.48  0.5  0.48  0.35  0.32    pp
333    USHA_ECOLI  0.61  0.60  0.48  0.5  0.44  0.39  0.38    pp
334    XYLF_ECOLI  0.59  0.61  0.48  0.5  0.42  0.42  0.37    pp
335    YTFQ_ECOLI  0.74  0.74  0.48  0.5  0.31  0.53  0.52    pp

[336 rows x 9 columns]


In [8]:
# Filter the dataset to include only rows where the 'class' column is either 'cp' or 'im'
filtered_df = readFile[readFile['class'].isin(['cp', 'im'])]

In [9]:
# Drop the 'Sequence Name' column since it is not relevant to the model
df = filtered_df.drop(columns=["Sequence Name"])


In [10]:
# Display the filtered dataset
print(df)

      mcg   gvh   lip  chg   aac  alm1  alm2 class
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35    cp
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44    cp
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46    cp
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36    cp
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35    cp
..    ...   ...   ...  ...   ...   ...   ...   ...
215  0.10  0.49  0.48  0.5  0.41  0.67  0.21    im
216  0.30  0.51  0.48  0.5  0.42  0.61  0.34    im
217  0.61  0.47  0.48  0.5  0.00  0.80  0.32    im
218  0.63  0.75  0.48  0.5  0.64  0.73  0.66    im
219  0.71  0.52  0.48  0.5  0.64  1.00  0.99    im

[220 rows x 8 columns]


In [11]:
df.shape #find the size of the data set rows and columns 

(220, 8)

In [12]:

# Convert 'cp' and 'im' to numerical values (0 and 1)
df['class'] = df['class'].map({"cp": 0, "im": 1})
print(df)

      mcg   gvh   lip  chg   aac  alm1  alm2  class
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35      0
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44      0
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46      0
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36      0
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35      0
..    ...   ...   ...  ...   ...   ...   ...    ...
215  0.10  0.49  0.48  0.5  0.41  0.67  0.21      1
216  0.30  0.51  0.48  0.5  0.42  0.61  0.34      1
217  0.61  0.47  0.48  0.5  0.00  0.80  0.32      1
218  0.63  0.75  0.48  0.5  0.64  0.73  0.66      1
219  0.71  0.52  0.48  0.5  0.64  1.00  0.99      1

[220 rows x 8 columns]


In [13]:
#find the amount of the cp and im 

In [14]:
df["class"].value_counts()

class
0    143
1     77
Name: count, dtype: int64

In [15]:
#add the standardscaler and traintest spilit 

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [17]:
#make the x and y  

In [18]:
x = df.drop(columns=['class'])  # Features
y = df['class']  # Target

In [19]:
print(x)

      mcg   gvh   lip  chg   aac  alm1  alm2
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35
..    ...   ...   ...  ...   ...   ...   ...
215  0.10  0.49  0.48  0.5  0.41  0.67  0.21
216  0.30  0.51  0.48  0.5  0.42  0.61  0.34
217  0.61  0.47  0.48  0.5  0.00  0.80  0.32
218  0.63  0.75  0.48  0.5  0.64  0.73  0.66
219  0.71  0.52  0.48  0.5  0.64  1.00  0.99

[220 rows x 7 columns]


In [20]:
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
215    1
216    1
217    1
218    1
219    1
Name: class, Length: 220, dtype: int64


In [21]:
# make the x and y to array 

In [22]:
x = np.array(x)

In [23]:
y = np.array(y)

In [24]:
print(x)

[[0.49 0.29 0.48 ... 0.56 0.24 0.35]
 [0.07 0.4  0.48 ... 0.54 0.35 0.44]
 [0.56 0.4  0.48 ... 0.49 0.37 0.46]
 ...
 [0.61 0.47 0.48 ... 0.   0.8  0.32]
 [0.63 0.75 0.48 ... 0.64 0.73 0.66]
 [0.71 0.52 0.48 ... 0.64 1.   0.99]]


In [25]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [26]:
#normalize
#make the data between the 0 and 1


In [27]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [28]:
print(x)

[[ 0.53507846 -1.53279614 -0.06757374 ...  0.73357223 -0.97320664
  -0.8017078 ]
 [-2.07120777 -0.40976657 -0.06757374 ...  0.54292144 -0.50442478
  -0.35780919]
 [ 0.9694595  -0.40976657 -0.06757374 ...  0.06629448 -0.41919172
  -0.25916505]
 ...
 [ 1.27973167  0.30488861 -0.06757374 ... -4.60464978  1.4133192
  -0.949674  ]
 [ 1.40384054  3.16350933 -0.06757374 ...  1.49617537  1.11500347
   0.72727631]
 [ 1.90027601  0.81535659 -0.06757374 ...  1.49617537  2.26564986
   2.35490456]]


In [29]:
#we spilite the train and the test data 

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [31]:
print(x_test.shape, y_test.shape)

(44, 7) (44,)


In [32]:
print(x_train.shape, y_train.shape)  

(176, 7) (176,)


In [33]:
#implemenation of Multilayer perceptron

In [34]:
# Define sigmoid function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)


In [36]:
class MLP:
    def __init__(self, input_size, hidden_size, output_size, learning_rate=0.01):
        # Initialize weights and biases
        self.inputSize = input_size
        self.hiddenSize = hidden_size
        self.outputSize = output_size
        self.learningRate = learning_rate

        # Initialize weights and biases for the layers
        self.weightInput = np.random.randn(input_size, hidden_size)
        self.weightOutput = np.random.randn(hidden_size, output_size)

        self.hiddenBias = np.zeros((1, hidden_size))
        self.outputBias = np.zeros((1, output_size))

    # Forward propagation
    def forward(self, x):
        # Compute input to the hidden layer
        self.hiddenInput = np.dot(x, self.weightInput) + self.hiddenBias
        self.hiddenOutput = sigmoid(self.hiddenInput)

        # Compute input to the output layer
        self.outputInput = np.dot(self.hiddenOutput, self.weightOutput) + self.outputBias
        self.outputOutput = sigmoid(self.outputInput)

        return self.outputOutput

    def backward(self, x, y, output):
        # Ensure y and output are the correct shape (reshape if needed)
        if y.ndim == 1:
            y = y.reshape(-1, 1)  # Reshape y to (batch_size, 1)

        # Calculate the output error (difference between actual and predicted)
        output_error = y - output

        # Calculate the gradient (delta) for the output layer
        outputDecent = output_error * sigmoid_derivative(output)

        # Calculate the hidden layer error
        hidden_error = np.dot(outputDecent, self.weightOutput.T)
        hiddenDecent = hidden_error * sigmoid_derivative(self.hiddenOutput)

        # Update weights and biases between hidden and output layer
        self.weightOutput += np.dot(self.hiddenOutput.T, outputDecent) * self.learningRate
        self.outputBias += np.sum(outputDecent, axis=0, keepdims=True) * self.learningRate

        # Update weights and biases between input and hidden layer
        self.weightInput += np.dot(x.T, hiddenDecent) * self.learningRate
        self.hiddenBias += np.sum(hiddenDecent, axis=0, keepdims=True) * self.learningRate

    # Train the MLP
    def fit(self, x, y, epochs=1000):
        for epoch in range(epochs):
            result = self.forward(x)
            self.backward(x, y, result)

    # Predict method
    def predict(self, X):
        output = self.forward(X)
        return (output > 0.5).astype(int)


# Initialize the MLP with the input size matching the number of features (7 features), hidden neurons, and 1 output for binary classification
mlp = MLP(input_size=7, hidden_size=4, output_size=1)

# Assuming `x_train`, `y_train`, `x_test`, and `y_test` are preprocessed and ready
mlp.fit(x_train, y_train, epochs=1000)

# Make predictions on the test data
y_pred = mlp.predict(x_test)

# Evaluate the accuracy of the model
accuracy = np.mean(y_pred == y_test)
print(f"Test Accuracy: {accuracy:.2f}")

print(y_pred)

Test Accuracy: 0.57
[[0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]]
